# ################
# L8 I/O Standards
# ################

set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_rx_n[7]}]

set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l8_tx_n[7]}]

set_property IOSTANDARD LVCMOS25 [get_ports i2c_l8_scl]
set_property IOSTANDARD LVCMOS25 [get_ports i2c_l8_sda]
set_property IOSTANDARD LVCMOS25 [get_ports i2c_l8_rst]
set_property IOSTANDARD LVCMOS25 [get_ports i2c_l8_int]

# ########################
# L8 Additional Properties
# ########################

# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[0]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[0]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[1]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[1]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[2]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[2]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[3]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[3]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[4]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[4]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[5]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[5]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[6]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[6]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_p[7]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l8_rx_n[7]}]

# ##################
# L8 Pin Assignments
# ##################

set_property PACKAGE_PIN AG32 [get_ports {sfp_l8_rx_p[0]}]
set_property PACKAGE_PIN AH32 [get_ports {sfp_l8_rx_n[0]}]
set_property PACKAGE_PIN AM23 [get_ports {sfp_l8_rx_p[1]}]
set_property PACKAGE_PIN AN23 [get_ports {sfp_l8_rx_n[1]}]
set_property PACKAGE_PIN AP26 [get_ports {sfp_l8_rx_p[2]}]
set_property PACKAGE_PIN AP27 [get_ports {sfp_l8_rx_n[2]}]
set_property PACKAGE_PIN AP29 [get_ports {sfp_l8_rx_p[3]}]
set_property PACKAGE_PIN AP30 [get_ports {sfp_l8_rx_n[3]}]
set_property PACKAGE_PIN AN29 [get_ports {sfp_l8_rx_p[4]}]
set_property PACKAGE_PIN AN30 [get_ports {sfp_l8_rx_n[4]}]
set_property PACKAGE_PIN AL29 [get_ports {sfp_l8_rx_p[5]}]
set_property PACKAGE_PIN AM30 [get_ports {sfp_l8_rx_n[5]}]
set_property PACKAGE_PIN AK34 [get_ports {sfp_l8_rx_p[6]}]
set_property PACKAGE_PIN AL34 [get_ports {sfp_l8_rx_n[6]}]
set_property PACKAGE_PIN AH34 [get_ports {sfp_l8_rx_p[7]}]
set_property PACKAGE_PIN AJ34 [get_ports {sfp_l8_rx_n[7]}]

set_property PACKAGE_PIN AK24 [get_ports {sfp_l8_tx_p[0]}]
set_property PACKAGE_PIN AL24 [get_ports {sfp_l8_tx_n[0]}]
set_property PACKAGE_PIN AN24 [get_ports {sfp_l8_tx_p[1]}]
set_property PACKAGE_PIN AP24 [get_ports {sfp_l8_tx_n[1]}]
set_property PACKAGE_PIN AN25 [get_ports {sfp_l8_tx_p[2]}]
set_property PACKAGE_PIN AP25 [get_ports {sfp_l8_tx_n[2]}]
set_property PACKAGE_PIN AN27 [get_ports {sfp_l8_tx_p[3]}]
set_property PACKAGE_PIN AN28 [get_ports {sfp_l8_tx_n[3]}]
set_property PACKAGE_PIN AP31 [get_ports {sfp_l8_tx_p[4]}]
set_property PACKAGE_PIN AP32 [get_ports {sfp_l8_tx_n[4]}]
set_property PACKAGE_PIN AM25 [get_ports {sfp_l8_tx_p[5]}]
set_property PACKAGE_PIN AM26 [get_ports {sfp_l8_tx_n[5]}]
set_property PACKAGE_PIN AN32 [get_ports {sfp_l8_tx_p[6]}]
set_property PACKAGE_PIN AP33 [get_ports {sfp_l8_tx_n[6]}]
set_property PACKAGE_PIN AJ32 [get_ports {sfp_l8_tx_p[7]}]
set_property PACKAGE_PIN AK32 [get_ports {sfp_l8_tx_n[7]}]

set_property PACKAGE_PIN AC32 [get_ports i2c_l8_scl]
set_property PACKAGE_PIN AC33 [get_ports i2c_l8_sda]
set_property PACKAGE_PIN AE31 [get_ports i2c_l8_rst]
set_property PACKAGE_PIN AE32 [get_ports i2c_l8_int]

# #################
# L12 I/O Standards
# #################

set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_rx_n[7]}]

set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {sfp_l12_tx_n[7]}]

set_property IOSTANDARD LVCMOS25 [get_ports i2c_l12_scl]
set_property IOSTANDARD LVCMOS25 [get_ports i2c_l12_sda]
set_property IOSTANDARD LVCMOS25 [get_ports i2c_l12_rst]
set_property IOSTANDARD LVCMOS25 [get_ports i2c_l12_int]

# #########################
# L12 Additional Properties
# #########################

# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[0]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[0]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[1]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[1]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[2]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[2]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[3]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[3]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[4]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[4]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[5]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[5]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[6]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[6]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_p[7]}]
# set_property DIFF_TERM TRUE [get_ports {sfp_l12_rx_n[7]}]

# ###################
# L12 Pin Assignments
# ###################

set_property PACKAGE_PIN T28 [get_ports {sfp_l12_rx_p[0]}]
set_property PACKAGE_PIN T29 [get_ports {sfp_l12_rx_n[0]}]
set_property PACKAGE_PIN R32 [get_ports {sfp_l12_rx_p[1]}]
set_property PACKAGE_PIN P32 [get_ports {sfp_l12_rx_n[1]}]
set_property PACKAGE_PIN N33 [get_ports {sfp_l12_rx_p[2]}]
set_property PACKAGE_PIN M33 [get_ports {sfp_l12_rx_n[2]}]
set_property PACKAGE_PIN P34 [get_ports {sfp_l12_rx_p[3]}]
set_property PACKAGE_PIN N34 [get_ports {sfp_l12_rx_n[3]}]
set_property PACKAGE_PIN M30 [get_ports {sfp_l12_rx_p[4]}]
set_property PACKAGE_PIN M31 [get_ports {sfp_l12_rx_n[4]}]
set_property PACKAGE_PIN L34 [get_ports {sfp_l12_rx_p[5]}]
set_property PACKAGE_PIN K34 [get_ports {sfp_l12_rx_n[5]}]
set_property PACKAGE_PIN F34 [get_ports {sfp_l12_rx_p[6]}]
set_property PACKAGE_PIN E34 [get_ports {sfp_l12_rx_n[6]}]
set_property PACKAGE_PIN J34 [get_ports {sfp_l12_rx_p[7]}]
set_property PACKAGE_PIN H34 [get_ports {sfp_l12_rx_n[7]}]

set_property PACKAGE_PIN T30 [get_ports {sfp_l12_tx_p[0]}]
set_property PACKAGE_PIN T31 [get_ports {sfp_l12_tx_n[0]}]
set_property PACKAGE_PIN U32 [get_ports {sfp_l12_tx_p[1]}]
set_property PACKAGE_PIN U33 [get_ports {sfp_l12_tx_n[1]}]
set_property PACKAGE_PIN R33 [get_ports {sfp_l12_tx_p[2]}]
set_property PACKAGE_PIN R34 [get_ports {sfp_l12_tx_n[2]}]
set_property PACKAGE_PIN T33 [get_ports {sfp_l12_tx_p[3]}]
set_property PACKAGE_PIN T34 [get_ports {sfp_l12_tx_n[3]}]
set_property PACKAGE_PIN P30 [get_ports {sfp_l12_tx_p[4]}]
set_property PACKAGE_PIN N30 [get_ports {sfp_l12_tx_n[4]}]
set_property PACKAGE_PIN K32 [get_ports {sfp_l12_tx_p[5]}]
set_property PACKAGE_PIN J32 [get_ports {sfp_l12_tx_n[5]}]
set_property PACKAGE_PIN F33 [get_ports {sfp_l12_tx_p[6]}]
set_property PACKAGE_PIN E33 [get_ports {sfp_l12_tx_n[6]}]
set_property PACKAGE_PIN H33 [get_ports {sfp_l12_tx_p[7]}]
set_property PACKAGE_PIN G33 [get_ports {sfp_l12_tx_n[7]}]

set_property PACKAGE_PIN A29 [get_ports i2c_l12_scl]
set_property PACKAGE_PIN A30 [get_ports i2c_l12_sda]
set_property PACKAGE_PIN C29 [get_ports i2c_l12_rst]
set_property PACKAGE_PIN C30 [get_ports i2c_l12_int]
